Ignore lines with status key
echo '{{ get_workflow_details_3.stdout }}' | grep succeeded ...

  "succeeded": true
  "status": "succeeded (16s elapsed)",
  "status": "succeeded (1s elapsed)",

Error in the failed e2e test indicates that one of the above status lines was erroneously used by assert_workflow_succeeded:

  ValueError: Objects not equal. Input: {u'status': u'succeeded (16s elapsed)'}, Expected: {u'succeeded': True}